In [1]:

#Question -1 

import pandas as pd
from IPython.display import display, HTML
pd.set_option('display.mpl_style', 'default')

def get_occupation(ocp=0):
      ocp_list = ["other or not specified", "academic/educator", "artist", "clerical-admin", "college/grad student",
                  "customer service","doctor/health care", "executive/managerial", "farmer", "homemaker", "K-12 student", 
                  "lawyer", "programmer", "retired", "sales/marketing", "scientist", "self-employed", "technician/engineer", 
                  "tradesman/craftsman", "unemployed", "writer"]
      return ocp_list[int(ocp)]
    
def get_age(age='1'):
    age_dict={'1':  "Under 18",
              '18':  "18-24",
              '25':  "25-34",
              '35':  "35-44",
              '45':  "45-49",
              '50':  "50-55",
              '56':  "56+"}
    return age_dict[str(age)]



def get_user_dataset():
    UserID,Gender,Age,Ocptn,zipcd = [],[],[],[],[]
    User_DataSet = pd.DataFrame()
    #UserID::MovieID::Rating::Timestamp
    with open('users.dat') as f:
        for line in f:
            line = str(line.strip()).split("::")
            UserID.append(line[0])
            Gender.append(line[1])
            Age.append(get_age(age=line[2]))
            Ocptn.append(get_occupation(ocp=line[3]))
            zipcd.append(line[4])
    User_DataSet["userID"] = UserID
    User_DataSet["gender"] = Gender
    User_DataSet["age"] = Age
    User_DataSet["ocptn"] = Ocptn
    User_DataSet["zipCD"] = zipcd
    return User_DataSet

def get_rating_dataset():
    R_UserID,R_MovieID,rating,TimeStamp = [],[],[],[]
    Rating_DataSet = pd.DataFrame()
    with open('ratings.dat') as f:
        #UserID::MovieID::Rating::Timestamp
        for line in f:
            line = str(line.strip()).split("::")
            R_UserID.append(line[0])
            R_MovieID.append(line[1])
            rating.append(line[2])
            TimeStamp.append(line[3])
    Rating_DataSet["userID"] = R_UserID
    Rating_DataSet["movieID"] = R_MovieID
    Rating_DataSet["rating"] = rating
    Rating_DataSet["timestamp"] = TimeStamp
    return Rating_DataSet

def get_movie_dataset():
    MovieID,Title,Genere = [],[],[]
    Movie_DataSet = pd.DataFrame()
    with open('movies.dat') as f:
        #MovieID::Title::Genres
        for line in f:
            line = str(line.strip()).split("::")
            MovieID.append(line[0])
            Title.append(line[1])
            Genere.append(line[2])
    Movie_DataSet["movieID"] = MovieID
    Movie_DataSet["genere"] = Title
    Movie_DataSet["title"] = Genere
    return Movie_DataSet

print "*** User Dataset ***"
User_DataSet = get_user_dataset()
display(User_DataSet)
print "*** Movie Dataset ***"
Movie_DataSet = get_movie_dataset()
display(Movie_DataSet)
print "*** Rating Dataset ***"
Rating_DataSet = get_rating_dataset()
display(Rating_DataSet)


#Merge User and rating table with left outer join
UR_result = pd.merge(User_DataSet, Rating_DataSet, how='inner', on='userID',left_index=False, right_index=False, sort=True,
               suffixes=('_x', '_y'), copy=True, indicator=False)
#Merge User+rating table with Movie table - left outer join
UR_M_result = pd.merge(UR_result, Movie_DataSet, how='inner', on='movieID',left_index=False, right_index=False, sort=True,
               suffixes=('_x', '_y'), copy=True, indicator=False)
#display(UR_result)
display(UR_M_result)

Merged_hdf_datastore = pd.HDFStore('Merged_hdf_datastore.h5')
print Merged_hdf_datastore
Merged_hdf_datastore['UMR_dataframe'] = UR_M_result
Merged_hdf_datastore
#Read from hdf5 to verify
readhdf = pd.read_hdf('Merged_hdf_datastore.h5','UMR_dataframe')  
print "*** Printing data from HDF5 ***"
readhdf

*** User Dataset ***

     userID gender       age                   ocptn  zipCD
0         1      F  Under 18            K-12 student  48067
1         2      M       56+           self-employed  70072
2         3      M     25-34               scientist  55117
3         4      M     45-49    executive/managerial  02460
4         5      M     25-34                  writer  55455
5         6      F     50-55               homemaker  55117
6         7      M     35-44       academic/educator  06810
7         8      M     25-34              programmer  11413
8         9      M     25-34     technician/engineer  61614
9        10      F     35-44       academic/educator  95370
10       11      F     25-34       academic/educator  04093
11       12      M     25-34              programmer  32793
12       13      M     45-49       academic/educator  93304
13       14      M     35-44  other or not specified  60126
14       15      M     25-34    executive/managerial  22903
15       16      F     35-44  other or not specified  20670
16       17      M     50-55       academic/educator  95350
17       18      F     18-24          clerical-admin  95825
18       19      M  Under 18            K-12 student  48073
19       20      M     25-34         sales/marketing  55113
20       21      M     18-24           self-employed  99353
21       22      M     18-24               scientist  53706
22       23      M     35-44  other or not specified  90049
23       24      F     25-34    executive/managerial  10023
24       25      M     18-24    college/grad student  01609
25       26      M     25-34    executive/managerial  23112
26       27      M     25-34                  lawyer  19130
27       28      F     25-34       academic/educator  14607
28       29      M     35-44    executive/managerial  33407
29       30      F     35-44    executive/managerial  19143
...     ...    ...       ...                     ...    ...
6010   6011      M     35-44               scientist  80538
6011   6012      M     35-44               scientist  02871
6012   6013      F     25-34                  writer  32301
6013   6014      M     45-49       academic/educator  80634
6014   6015      F     25-34               homemaker  80013
6015   6016      M     45-49       academic/educator  37209
6016   6017      F     35-44    executive/managerial  21117
6017   6018      M     35-44       academic/educator  48906
6018   6019      M     25-34  other or not specified  10024
6019   6020      M     50-55           self-employed  10023
6020   6021      M     25-34              programmer  08876
6021   6022      M     25-34     technician/engineer  57006
6022   6023      M     25-34  other or not specified  43213
6023   6024      M     25-34              programmer  53705
6024   6025      F     25-34       academic/educator  32607
6025   6026      M     35-44      doctor/health care  11210
6026   6027      M     18-24    college/grad student  20742
6027   6028      M     18-24    college/grad student  94133
6028   6029      F     25-34       academic/educator  23185
6029   6030      M     25-34     technician/engineer  32618
6030   6031      F     18-24  other or not specified  45123
6031   6032      M     45-49    executive/managerial  55108
6032   6033      M     50-55                 retired  78232
6033   6034      M     25-34         sales/marketing  94117
6034   6035      F     25-34       academic/educator  78734
6035   6036      F     25-34               scientist  32603
6036   6037      F     45-49       academic/educator  76006
6037   6038      F       56+       academic/educator  14706
6038   6039      F     45-49  other or not specified  01060
6039   6040      M     25-34      doctor/health care  11106

[6040 rows x 5 columns]

*** Movie Dataset ***

,movieID,genere,title
0,1,Toy Story (1995),Animation|Children's|Comedy
1,2,Jumanji (1995),Adventure|Children's|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children's
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller
10,11,"American President, The (1995)",Comedy|Drama|Romance
11,12,Dracula: Dead and Loving It (1995),Comedy|Horror
12,13,Balto (1995),Animation|Children's
13,14,Nixon (1995),Drama
14,15,Cutthroat Island (1995),Action|Adventure|Romance
15,16,Casino (1995),Drama|Thriller
16,17,Sense and Sensibility (1995),Drama|Romance
17,18,Four Rooms (1995),Thriller
18,19,Ace Ventura: When Nature Calls (1995),Comedy
19,20,Money Train (1995),Action
20,21,Get Shorty (1995),Action|Comedy|Drama
21,22,Copycat (1995),Crime|Drama|Thriller
22,23,Assassins (1995),Thriller
23,24,Powder (1995),Drama|Sci-Fi
24,25,Leaving Las Vegas (1995),Drama|Romance
25,26,Othello (1995),Drama
26,27,Now and Then (1995),Drama
27,28,Persuasion (1995),Romance
28,29,"City of Lost Children, The (1995)",Adventure|Sci-Fi
29,30,Shanghai Triad (Yao a yao yao dao waipo qiao) ...,Drama
...,...,...,...
3853,3923,Return of the Fly (1959),Horror|Sci-Fi
3854,3924,Pajama Party (1964),Comedy
3855,3925,Stranger Than Paradise (1984),Comedy
3856,3926,Voyage to the Bottom of the Sea (1961),Adventure|Sci-Fi
3857,3927,Fantastic Voyage (1966),Adventure|Sci-Fi
3858,3928,Abbott and Costello Meet Frankenstein (1948),Comedy|Horror
3859,3929,"Bank Dick, The (1940)",Comedy
3860,3930,"Creature From the Black Lagoon, The (1954)",Horror
3861,3931,"Giant Gila Monster, The (1959)",Horror|Sci-Fi
3862,3932,"Invisible Man, The (1933)",Horror|Sci-Fi
3863,3933,"Killer Shrews, The (1959)",Horror|Sci-Fi
3864,3934,Kronos (1957),Sci-Fi
3865,3935,Kronos (1973),Horror
3866,3936,"Phantom of the Opera, The (1943)",Drama|Thriller
3867,3937,Runaway (1984),Sci-Fi|Thriller
3868,3938,"Slumber Party Massacre, The (1982)",Horror
3869,3939,"Slumber Party Massacre II, The (1987)",Horror
3870,3940,"Slumber Party Massacre III, The (1990)",Horror
3871,3941,Sorority House Massacre (1986),Horror
3872,3942,Sorority House Massacre II (1990),Horror
3873,3943,Bamboozled (2000),Comedy
3874,3944,Bootmen (2000),Comedy|Drama
3875,3945,Digimon: The Movie (2000),Adventure|Animation|Children's
3876,3946,Get Carter (2000),Action|Drama|Thriller
3877,3947,Get Carter (1971),Thriller
3878,3948,Meet the Parents (2000),Comedy
3879,3949,Requiem for a Dream (2000),Drama
3880,3950,Tigerland (2000),Drama
3881,3951,Two Family House (2000),Drama
3882,3952,"Contender, The (2000)",Drama|Thriller

*** Rating Dataset ***

        userID movieID rating  timestamp
0            1    1193      5  978300760
1            1     661      3  978302109
2            1     914      3  978301968
3            1    3408      4  978300275
4            1    2355      5  978824291
5            1    1197      3  978302268
6            1    1287      5  978302039
7            1    2804      5  978300719
8            1     594      4  978302268
9            1     919      4  978301368
10           1     595      5  978824268
11           1     938      4  978301752
12           1    2398      4  978302281
13           1    2918      4  978302124
14           1    1035      5  978301753
15           1    2791      4  978302188
16           1    2687      3  978824268
17           1    2018      4  978301777
18           1    3105      5  978301713
19           1    2797      4  978302039
20           1    2321      3  978302205
21           1     720      3  978300760
22           1    1270      5  978300055
23           1     527      5  978824195
24           1    2340      3  978300103
25           1      48      5  978824351
26           1    1097      4  978301953
27           1    1721      4  978300055
28           1    1545      4  978824139
29           1     745      3  978824268
...        ...     ...    ...        ...
1000179   6040    2762      4  956704584
1000180   6040    1036      3  956715455
1000181   6040     508      4  956704972
1000182   6040    1041      4  957717678
1000183   6040    3735      4  960971654
1000184   6040    2791      4  956715569
1000185   6040    2794      1  956716438
1000186   6040     527      5  956704219
1000187   6040    2003      1  956716294
1000188   6040     535      4  964828734
1000189   6040    2010      5  957716795
1000190   6040    2011      4  956716113
1000191   6040    3751      4  964828782
1000192   6040    2019      5  956703977
1000193   6040     541      4  956715288
1000194   6040    1077      5  964828799
1000195   6040    1079      2  956715648
1000196   6040     549      4  956704746
1000197   6040    2020      3  956715288
1000198   6040    2021      3  956716374
1000199   6040    2022      5  956716207
1000200   6040    2028      5  956704519
1000201   6040    1080      4  957717322
1000202   6040    1089      4  956704996
1000203   6040    1090      3  956715518
1000204   6040    1091      1  956716541
1000205   6040    1094      5  956704887
1000206   6040     562      5  956704746
1000207   6040    1096      4  956715648
1000208   6040    1097      4  956715569

[1000209 rows x 4 columns]

,userID,gender,age,ocptn,zipCD,movieID,rating,timestamp,genere,title
0,1,F,Under 18,K-12 student,48067,1,5,978824268,Toy Story (1995),Animation|Children's|Comedy
1,10,F,35-44,academic/educator,95370,1,5,978226474,Toy Story (1995),Animation|Children's|Comedy
2,1000,F,25-34,doctor/health care,90027,1,5,975041651,Toy Story (1995),Animation|Children's|Comedy
3,1001,M,25-34,college/grad student,90210,1,4,976296608,Toy Story (1995),Animation|Children's|Comedy
4,1004,M,25-34,clerical-admin,95136,1,5,975045804,Toy Story (1995),Animation|Children's|Comedy
5,1008,M,35-44,clerical-admin,77064,1,4,975030379,Toy Story (1995),Animation|Children's|Comedy
6,1010,M,25-34,other or not specified,10310,1,2,975220910,Toy Story (1995),Animation|Children's|Comedy
7,1014,F,45-49,technician/engineer,03054,1,3,975015612,Toy Story (1995),Animation|Children's|Comedy
8,1015,M,35-44,clerical-admin,11220,1,5,975017987,Toy Story (1995),Animation|Children's|Comedy
9,1017,M,35-44,other or not specified,30906,1,4,975009586,Toy Story (1995),Animation|Children's|Comedy
10,1021,M,35-44,other or not specified,94559,1,5,975008082,Toy Story (1995),Animation|Children's|Comedy
11,1029,M,25-34,other or not specified,20015,1,4,980037417,Toy Story (1995),Animation|Children's|Comedy
12,1032,M,50-55,self-employed,19425,1,5,974997699,Toy Story (1995),Animation|Children's|Comedy
13,1036,M,35-44,executive/managerial,28036,1,5,974991657,Toy Story (1995),Animation|Children's|Comedy
14,1044,M,25-34,writer,72701,1,3,975570555,Toy Story (1995),Animation|Children's|Comedy
15,1045,F,Under 18,K-12 student,77477,1,4,974965960,Toy Story (1995),Animation|Children's|Comedy
16,1050,M,25-34,academic/educator,97302,1,4,974963037,Toy Story (1995),Animation|Children's|Comedy
17,1051,F,25-34,other or not specified,60513,1,5,974959121,Toy Story (1995),Animation|Children's|Comedy
18,1054,M,Under 18,K-12 student,75040,1,5,975101862,Toy Story (1995),Animation|Children's|Comedy
19,1055,M,35-44,other or not specified,91505,1,5,974953210,Toy Story (1995),Animation|Children's|Comedy
20,1056,M,Under 18,other or not specified,48133,1,4,974953275,Toy Story (1995),Animation|Children's|Comedy
21,1057,M,45-49,technician/engineer,73069,1,5,974952896,Toy Story (1995),Animation|Children's|Comedy
22,1059,F,25-34,other or not specified,97213,1,5,974953956,Toy Story (1995),Animation|Children's|Comedy
23,1061,M,45-49,other or not specified,46060,1,5,974950066,Toy Story (1995),Animation|Children's|Comedy
24,1062,M,50-55,unemployed,59457,1,4,975050353,Toy Story (1995),Animation|Children's|Comedy
25,1063,M,35-44,executive/managerial,50265,1,4,974947400,Toy Story (1995),Animation|Children's|Comedy
26,1068,F,18-24,college/grad student,77581,1,3,975015029,Toy Story (1995),Animation|Children's|Comedy
27,1072,F,35-44,executive/managerial,07601,1,5,974941593,Toy Story (1995),Animation|Children's|Comedy
28,1074,M,45-49,technician/engineer,48073,1,4,974940870,Toy Story (1995),Animation|Children's|Comedy
29,1076,F,25-34,clerical-admin,27606,1,5,974938627,Toy Story (1995),Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000179,5601,M,35-44,academic/educator,98225,999,5,959211822,2 Days in the Valley (1996),Crime
1000180,5621,M,25-34,executive/managerial,02135,999,3,959106997,2 Days in the Valley (1996),Crime
1000181,5645,M,25-34,artist,87123,999,3,958926000,2 Days in the Valley (1996),Crime
1000182,5659,M,25-34,other or not specified,20874,999,3,958790615,2 Days in the Valley (1996),Crime
1000183,5675,M,35-44,sales/marketing,30030,999,4,958684911,2 Days in the Valley (1996),Crime
1000184,5678,M,35-44,technician/engineer,98103,999,2,958627607,2 Days in the Valley (1996),Crime
1000185,5682,M,18-24,other or not specified,23455-4959,999,4,1029456715,2 Days in the Valley (1996),Crime
1000186,5717,M,25-34,other or not specified,03766,999,3,958756833,2 Days in the Valley (1996),Crime
1000187,5837,M,25-34,executive/managerial,60607,999,4,958144635,2 Days in the Valley (1996),Crime
1000188,5847,F,18-24,college/grad student,02464,999,5,957794101,2 Days in the Valley (1996),Crime
1000189,5880,M,25-34,academic/educator,08904,999,2,959182969,2 Days in the Valley (1996),Crime
1000190,5961,F,45-49,other or not specified,78757,999,4,957025535,2 Days in the Valley (1996),Crime
1000191,5963,M,25-34,scientist,02140,999,2,957235138,2 Days in the Valley (1996),Crime
1000192,6001,F,25-34,executive/managerial,94117,999,4,956808090,2 Days in the Valley (1996),Crime
1000193,6010,M,35-44,other or not specified,79606,999,4,957464620,2 Days in the Valley (1996),Crime
1000194,6016,M,45-49,academic/educator,37209,999,2,956779685,2 Days in the Valley (1996),Crime
1000195,6036,F,25-34,scientist,32603,999,3,956716596,2 Days in the Valley (1996),Crime
1000196,651,M,35-44,executive/managerial,20895,999,3,975707440,2 Days in the Valley (1996),Crime
1000197,676,M,18-24,self-employed,55129,999,1,975687081,2 Days in the Valley (1996),Crime
1000198,692,F,25-34,other or not specified,85207,999,4,978387620,2 Days in the Valley (1996),Crime
1000199,710,M,25-34,writer,85207,999,4,975542061,2 Days in the Valley (1996),Crime
1000200,716,M,18-24,college/grad student,98188,999,3,982881919,2 Days in the Valley (1996),Crime
1000201,721,F,35-44,homemaker,97520,999,4,975775529,2 Days in the Valley (1996),Crime
1000202,817,M,18-24,college/grad student,41076,999,4,975390132,2 Days in the Valley (1996),Crime
1000203,90,M,56+,retired,85749,999,4,993873274,2 Days in the Valley (1996),Crime
1000204,929,M,25-34,scientist,53706,999,3,975566287,2 Days in the Valley (1996),Crime
1000205,930,M,25-34,customer service,98380,999,2,975190639,2 Days in the Valley (1996),Crime
1000206,963,M,25-34,other or not specified,48197,999,2,975207815,2 Days in the Valley (1996),Crime
1000207,971,M,25-34,programmer,43615,999,3,975111055,2 Days in the Valley (1996),Crime
1000208,996,M,25-34,technician/engineer,98102,999,3,977561172,2 Days in the Valley (1996),Crime

<class 'pandas.io.pytables.HDFStore'>
File path: Merged_hdf_datastore.h5
Empty
*** Printing data from HDF5 ***

,userID,gender,age,ocptn,zipCD,movieID,rating,timestamp,genere,title
0,1,F,Under 18,K-12 student,48067,1,5,978824268,Toy Story (1995),Animation|Children's|Comedy
1,10,F,35-44,academic/educator,95370,1,5,978226474,Toy Story (1995),Animation|Children's|Comedy
2,1000,F,25-34,doctor/health care,90027,1,5,975041651,Toy Story (1995),Animation|Children's|Comedy
3,1001,M,25-34,college/grad student,90210,1,4,976296608,Toy Story (1995),Animation|Children's|Comedy
4,1004,M,25-34,clerical-admin,95136,1,5,975045804,Toy Story (1995),Animation|Children's|Comedy
5,1008,M,35-44,clerical-admin,77064,1,4,975030379,Toy Story (1995),Animation|Children's|Comedy
6,1010,M,25-34,other or not specified,10310,1,2,975220910,Toy Story (1995),Animation|Children's|Comedy
7,1014,F,45-49,technician/engineer,03054,1,3,975015612,Toy Story (1995),Animation|Children's|Comedy
8,1015,M,35-44,clerical-admin,11220,1,5,975017987,Toy Story (1995),Animation|Children's|Comedy
9,1017,M,35-44,other or not specified,30906,1,4,975009586,Toy Story (1995),Animation|Children's|Comedy
10,1021,M,35-44,other or not specified,94559,1,5,975008082,Toy Story (1995),Animation|Children's|Comedy
11,1029,M,25-34,other or not specified,20015,1,4,980037417,Toy Story (1995),Animation|Children's|Comedy
12,1032,M,50-55,self-employed,19425,1,5,974997699,Toy Story (1995),Animation|Children's|Comedy
13,1036,M,35-44,executive/managerial,28036,1,5,974991657,Toy Story (1995),Animation|Children's|Comedy
14,1044,M,25-34,writer,72701,1,3,975570555,Toy Story (1995),Animation|Children's|Comedy
15,1045,F,Under 18,K-12 student,77477,1,4,974965960,Toy Story (1995),Animation|Children's|Comedy
16,1050,M,25-34,academic/educator,97302,1,4,974963037,Toy Story (1995),Animation|Children's|Comedy
17,1051,F,25-34,other or not specified,60513,1,5,974959121,Toy Story (1995),Animation|Children's|Comedy
18,1054,M,Under 18,K-12 student,75040,1,5,975101862,Toy Story (1995),Animation|Children's|Comedy
19,1055,M,35-44,other or not specified,91505,1,5,974953210,Toy Story (1995),Animation|Children's|Comedy
20,1056,M,Under 18,other or not specified,48133,1,4,974953275,Toy Story (1995),Animation|Children's|Comedy
21,1057,M,45-49,technician/engineer,73069,1,5,974952896,Toy Story (1995),Animation|Children's|Comedy
22,1059,F,25-34,other or not specified,97213,1,5,974953956,Toy Story (1995),Animation|Children's|Comedy
23,1061,M,45-49,other or not specified,46060,1,5,974950066,Toy Story (1995),Animation|Children's|Comedy
24,1062,M,50-55,unemployed,59457,1,4,975050353,Toy Story (1995),Animation|Children's|Comedy
25,1063,M,35-44,executive/managerial,50265,1,4,974947400,Toy Story (1995),Animation|Children's|Comedy
26,1068,F,18-24,college/grad student,77581,1,3,975015029,Toy Story (1995),Animation|Children's|Comedy
27,1072,F,35-44,executive/managerial,07601,1,5,974941593,Toy Story (1995),Animation|Children's|Comedy
28,1074,M,45-49,technician/engineer,48073,1,4,974940870,Toy Story (1995),Animation|Children's|Comedy
29,1076,F,25-34,clerical-admin,27606,1,5,974938627,Toy Story (1995),Animation|Children's|Comedy
...,...,...,...,...,...,...,...,...,...,...
1000179,5601,M,35-44,academic/educator,98225,999,5,959211822,2 Days in the Valley (1996),Crime
1000180,5621,M,25-34,executive/managerial,02135,999,3,959106997,2 Days in the Valley (1996),Crime
1000181,5645,M,25-34,artist,87123,999,3,958926000,2 Days in the Valley (1996),Crime
1000182,5659,M,25-34,other or not specified,20874,999,3,958790615,2 Days in the Valley (1996),Crime
1000183,5675,M,35-44,sales/marketing,30030,999,4,958684911,2 Days in the Valley (1996),Crime
1000184,5678,M,35-44,technician/engineer,98103,999,2,958627607,2 Days in the Valley (1996),Crime
1000185,5682,M,18-24,other or not specified,23455-4959,999,4,1029456715,2 Days in the Valley (1996),Crime
1000186,5717,M,25-34,other or not specified,03766,999,3,958756833,2 Days in the Valley (1996),Crime
1000187,5837,M,25-34,executive/managerial,60607,999,4,958144635,2 Days in the Valley (1996),Crime
1000188,5847,F,18-24,college/grad student,02464,999,5,957794101,2 Days in the Valley (1996),Crime
1000189,5880,M,25-34,academic/educator,08904,999,2,959182969,2 Days in the Valley (1996),Crime
1000190,5961,F,45-49,other or not specified,78757,999,4,957025535,2 Days in the Valley (1996),Crime
1000191,5963,M,25-34,scientist,02140,999,2,957235138,2 Days in the Valley (1996),Crime
1000192,6001,F,25-34,executive/managerial,94117,999,4,956808090,2 Days in the Valley (1996),Crime
1000193,6010,M,35-44,other or not specified,79606,999,4,957464620,2 Days in the Valley (1996),Crime
1000194,6016,M,45-49,academic/educator,37209,999,2,956779685,2 Days in the Valley (1996),Crime
1000195,6036,F,25-34,scientist,32603,999,3,956716596,2 Days in the Valley (1996),Crime
1000196,651,M,35-44,executive/managerial,20895,999,3,975707440,2 Days in the Valley (1996),Crime
1000197,676,M,18-24,self-employed,55129,999,1,975687081,2 Days in the Valley (1996),Crime
1000198,692,F,25-34,other or not specified,85207,999,4,978387620,2 Days in the Valley (1996),Crime
1000199,710,M,25-34,writer,85207,999,4,975542061,2 Days in the Valley (1996),Crime
1000200,716,M,18-24,college/grad student,98188,999,3,982881919,2 Days in the Valley (1996),Crime
1000201,721,F,35-44,homemaker,97520,999,4,975775529,2 Days in the Valley (1996),Crime
1000202,817,M,18-24,college/grad student,41076,999,4,975390132,2 Days in the Valley (1996),Crime
1000203,90,M,56+,retired,85749,999,4,993873274,2 Days in the Valley (1996),Crime
1000204,929,M,25-34,scientist,53706,999,3,975566287,2 Days in the Valley (1996),Crime
1000205,930,M,25-34,customer service,98380,999,2,975190639,2 Days in the Valley (1996),Crime
1000206,963,M,25-34,other or not specified,48197,999,2,975207815,2 Days in the Valley (1996),Crime
1000207,971,M,25-34,programmer,43615,999,3,975111055,2 Days in the Valley (1996),Crime
1000208,996,M,25-34,technician/engineer,98102,999,3,977561172,2 Days in the Valley (1996),Crime